### ISSUE TITLE
Create Base code for unsupervised unet

### ISSUE THREAD

**Issue by TerenceTYAranowitz** [UC-Irvine-CS175/final-project-e-mcheese-2#12]
#### Description
Import base code of unsupervised unet model and adapt for our project repository.

#### Files
src/models/unsupervised/unet/*

#### Tasks
- [ ] create new directory src/models/unsupervised/unet/*
- [ ] port unet basecode
- [ ] adapt to make it compatible with our repo, file locations, shape, etc
