### ISSUE TITLE
Repository Setup

### ISSUE THREAD

**Issue by JarrodRShepherd** [UC-Irvine-CS175/final-project-e-mcheese-2#2]
#### Description 
Port the files from Homework 1 into this repository, and adapt bps_dataset.py for our model. Also set up the structure for this repository and the associated environment.

#### Files
- data_utils.py
- bps_dataset.py
- augmentation.py

#### Tasks
- [x] Create the overall structure of the repository. These include the directories "src", "data", "setup", and "tests," along with a .gitignore file.
- [x] Add yaml files for setting up the environment. 
- [x] Port files into the "src" directory of this repository. 
- [x] Modify bps_dataset.py to return an image, not a Tensor object.

**Comment by TerenceTYAranowitz** [comment]
Looks good!
