### ISSUE TITLE
move watershed class to ownfile

### ISSUE THREAD

**Issue by TerenceTYAranowitz** [UC-Irvine-CS175/final-project-e-mcheese-2#8]
#### Description
 Move the watershed class from augmentation.py to its own python file in a models directory.

#### Files
watershed.py
augmentation.py

#### Tasks
- [x] create a directory in src called models
- [x] move the watershed class into there
- [x] add latest updates to watershed from test-05 as well
